# Introduction to Python
###  ---------- A language that is just write then run and is 5~10 times shorter than C++

In [8]:
# Zhengjia Huang
# 06-07-2017
# INVETT Research Group, UAH, Spain

## 0. About python
  - python is slow
  - python is fast (easy to lerarn, short to wirte, simple to run)
  - python has a huge community
  - python is extremely popular in AI and Data Science

![poluparity.png](imgs/language.png)

## 1. Basics

### Say hello to the world in just one single line!

In [9]:
print('Hola Mundo!')

Hola Mundo!


### Declare variables and python will assign the type automatically.

In [4]:
a = 10
b = 3.14
c = "Hola Mundo!"

In [5]:
print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'float'>
<class 'str'>


### There is no "begin-end"! You use elegant indentation to specify blocks.

In [33]:
if a > b:
    while(a > 5):
        a = a - 1
    print('a was greater than b')
else:
    while(b < 5):
        b = b + 1
    print('b was greater than a')

a was greater than b


## 2. Data Types

In [7]:
# Integer
a = 1
print(a)

# Float
b = 1.0
print(b)

# String
c = "Hello world"
print(c)

# Unicode
d = u"你好"
print(d)

# List (array)
e = [1, 3.14, "I am a string"]
print(e)

# Tuple (constant array)
f = (1, 3.14, "I am a string")
print(f)

# Set
g = {1, 1, 1, 2, 'aaa'}
print(g)

# Dictionary (hash table, hash map)
h = {1:'One', 'Uno':'One', 'One':1}
print(h)

1
1.0
Hello world
你好
[1, 3.14, 'I am a string']
(1, 3.14, 'I am a string')
{1, 2, 'aaa'}
{'One': 1, 1: 'One', 'Uno': 'One'}


### Get access to values in list, tuple or dictionary

In [36]:
print(e[0])
print(f[1])
print(h['Uno'])
e[0] = 1000
print(e[0:2])

1000
3.14
One
[1000, 3.14]


## 3. Logic expressions

### For

In [8]:
for i in range(2, 10, 2):
    print(i)

2
4
6
8


### While

In [54]:
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


### Enumerate

In [10]:
items = ['apple', 'banana', 'stawberry', 'watermelon']
for item in items:
    print(item)

apple
banana
stawberry
watermelon


In [11]:
for i, item in enumerate(items):
    print(i, item)

0 apple
1 banana
2 stawberry
3 watermelon


### If

In [37]:
a = 65
if a >= 90:
    print('A')
elif a >= 80:
    print('B')
elif a >= 70:
    print('C')
elif a >= 60:
    print('D')
else:
    print('F')

D


### Try

In [10]:

try:
    INVETT > 10
except:
    print('What? I am innocent. I did nothing wrong~')
    

What? I am innocent. I did nothing wrong~


## 4. Import other libraries

In [47]:
import numpy
matrix = numpy.zeros([3,4])
print(matrix)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [49]:
import numpy as np
matrix = np.zeros([3,4])
print(matrix)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [52]:
from numpy import zeros
matrix = zeros([3,4])
print(matrix)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [53]:
from numpy import *
matrix = zeros([3,4])
print(matrix)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


## 5. Objective programming

### Function

In [11]:
def whoWin(boyFriendScore, girlFriendScore):
    if girlFriendScore > boyFriendScore:
        print('Girl Friend Wins!')
        return girlFriendScore, boyFriendScore
    else:
        print('Still Girl Friend Wins!')
        return girlFriendScore, boyFriendScore

In [12]:
winnerScore, LoserScore = whoWin(100, 60)
print(winnerScore, LoserScore)

Still Girl Friend Wins!
60 100


### Class

In [10]:
class animal():
    def __init__(self, name, age):
        self.age = age  # in a unit of year
        self.name = name
    
    def getName(self):
        return self.name
    
    def getAge(self):
        return self.age

In [11]:
alian = animal('ET', 1e10)
age = alian.getAge()
print(age)

10000000000.0


### Class inheritance

In [80]:
class puppy(animal):
    def __init__(self, name, age, hobby):
        animal.__init__(self, name, age)
        self.hobby = hobby
    
    def play(self):
        print(self.name, 'is', self.hobby)

In [82]:
myDog = puppy('meatBall', 0.1, 'eating my toe')
myDog.play()

meatBall is eating my toe


## One last thing ...

In [ ]:
# Python3 and Python2 are slightly different

python3 print('String') ==> python2 print 'String'
python3 1/3 = 0.333333  ==> python2 1/3 = 0

In [17]:
a = [1,2,3]
a.insert(0,1000)
print(a)

[1000, 1, 2, 3]


# Enjoy writing python!

![logo](imgs/logo.png)